### ISSUE TITLE
How to use in a universal react app

### ISSUE THREAD

**Issue by haovn577** [searchkit/searchkit#203]
This searchkit is awesome!
But how to use in a universal app, was render from server side?
Follow the structure: https://github.com/erikras/react-redux-universal-hot-example 

Got this error:
` [piping] error given was: Invariant Violation: Browser history needs a DOM
[1]     at Object.invariant [as default] (/home/hao/working/nearest/node_modules/invariant/invariant.js:42:15)
[1]     at createBrowserHistory (/home/hao/working/nearest/node_modules/searchkit/node_modules/history/lib/createBrowserHistory.js:41:100)
[1]     at /home/hao/working/nearest/node_modules/searchkit/node_modules/history/lib/useQueries.js:55:19
[1]     at Object.exports.createHistory (/home/hao/working/nearest/node_modules/searchkit/lib/src/core/history.js:5:57)
[1]     at new SearchkitManager (/home/hao/working/nearest/node_modules/searchkit/lib/src/core/SearchkitManager.js:46:38)
[1]     at Home.render (Home.js:12:23)
[1]     at Home.tryRender (/home/hao/working/nearest/node_modules/react-transform-catch-errors/lib/index.js:34:31)
[1]     at [object Object].ReactCompositeComponentMixin._renderValidatedComponentWithoutOwnerOrContext (/home/hao/working/nearest/node_modules/react/lib/ReactCompositeComponent.js:587:34)
[1]     at [object Object].ReactCompositeComponentMixin._renderValidatedComponent (/home/hao/working/nearest/node_modules/react/lib/ReactCompositeComponent.js:607:32)
[1]     at [object Object].wrapper [as _renderValidatedComponent] (/home/hao/working/nearest/node_modules/react/lib/ReactPerf.js:66:21)
`

Thanks,
Hao Tran

**Comment by joemcelroy** [comment]
Thanks. We are planning on this in a future release. This issue is tracked in issue #4
