### ISSUE TITLE
Searchkit in Universal App  

### ISSUE THREAD

**Issue by m1n5k** [searchkit/searchkit#4]

**Comment by joemcelroy** [comment]
This and react native we want to investigate soon. Thanks for heads up. Can you identify the main issues?

**Comment by m1n5k** [comment]
1. Require css file in component
2. window object in component

**Comment by SabeehY** [comment]
Any updates on this?

**Comment by joemcelroy** [comment]
Not yet, we need to do a spike on this soon.

**Comment by thomasmodeneis** [comment]
+1, great must have feature.

**Comment by thomasmodeneis** [comment]
First issue I've found when trying to render server side is:
```
something went wrong... --> Invariant Violation: Browser history needs a DOM at Object.invariant [as default] (/opt/---/node_modules/searchkit/node_modules/invariant/invariant.js:42:15) at createBrowserHistory (/opt/---/node_modules/searchkit/node_modules/history/lib/createBrowserHistory.js:39:100) at /opt/---/node_modules/searchkit/node_modules/history/lib/useQueries.js:47:19 at Object.exports.createHistory (/opt/---/node_modules/searchkit/lib/src/core/history.js:5:57) at SearchkitManager.setupListeners (/opt/---/node_modules/searchkit/lib/src/core/SearchkitManager.js:58:38) at SearchkitProvider.componentWillMount 
```
Problematic code:
`this.history = history_1.createHistory();`

I've managed to pass by this one by disabling history: `useHistory:false`

Second was the CSS styling that I've managed to solve with another if on server rendering code to check for search url and if true, send to index.ejs the searchkit css and this cleared the issue.

I can see the component is working server side now with this two fixes but the search result is not being fetched correctly. it seems like the query argument is not being consumed properly by the searchkit via server-side, somehow I need to debug more to understand what happens and make sure this argument can be consumed and the fetch then occurs correctly.

**Comment by joemcelroy** [comment]
Great! Thanks for having a quick look. Could you share your universal project using searchkit? we can help debug too if you commit.

**Comment by thomasmodeneis** [comment]
I can't share this one, but I can work on a basic fork to get you going with this asap.

**Comment by thomasmodeneis** [comment]
I've created this project with the setup for the react, its already working for basics but we will need to work on searchkit in order to have this app fully working! 
https://github.com/thomasmodeneis/searchkit-universal

Thanks in advance for the help debugging this :).

**Comment by dnordberg** [comment]
Perhaps this can help. Referencing mjackson:

https://github.com/ReactTraining/history/issues/80

"In a non-DOM environment (like node) you need to use a "memory history", not a "browser history"."

Perhaps searchkit could test for DOM and select the right history function.
```
const history = require('history');
const ExecutionEnvironment = require('react/node_modules/fbjs/lib/ExecutionEnvironment');
var historyObject = ExecutionEnvironment.canUseDOM ? history.createHistory : history.createMemoryHistory;
```

**Comment by joemcelroy** [comment]
Yeh actually we are looking at being able to provide your own history. Noticed a couple of forks wanted this feature. Thanks!

**Comment by Jaikant** [comment]
Anyone debugging this issue actively, would like to help.

**Comment by thejmazz** [comment]
To get around the `Only a single instance of BaseQueryAccessor is allowed` issue, you need to create a `new SearchkitManager` on each request (similar to how you make a fresh redux store).

However, I am getting a mismatch between server render and client render, for the ID of the input div:

![image](https://cloud.githubusercontent.com/assets/1270998/24635471/91f6839c-18a1-11e7-9733-278eb45d63b6.png)
![image](https://cloud.githubusercontent.com/assets/1270998/24635503/b489542a-18a1-11e7-8799-ef13142b4b9e.png)

**Comment by ssetem** [comment]
its on our list to make fully server renderable with good example repo

**Comment by Jaikant** [comment]
@thejmazz i have been doing some tests for server render, in my tests I found that the html which the server sends does not contains the html for the results. It is always "0 results found", and once on the browser the query result is populated. 
Btw, I bypassed the "Only a single instance of BaseQueryAccessor is allowed" by not having the SearchBox component.

**Comment by sidharthchugh** [comment]
any update on this issue?

**Comment by joemcelroy** [comment]
No update yet unfortunately.

**Comment by sidharthchugh** [comment]
Okay :(, I live in Berlin, Germany and I have seen many startups are moving to universal apps and for sure need search and I think so searchkit is perfect for their needs. It would be good if you guys can at least provide some work around.

**Comment by joemcelroy** [comment]
yeh I understand, its one of our priority issues.

**Comment by joemcelroy** [comment]
Hey all,

So ash has managed to get server side rendering of searchkit components using nextjs. It works but needs refactoring to push some of the hydrating logic down into searchkit core.

https://github.com/searchkit/searchkit-universal

**Comment by joemcelroy** [comment]
I'll do a blog post with some of the issues we encountered and issues remaining.

**Comment by thomasmodeneis** [comment]
Oh this is really good news.

Thanks for sharing @joemcelroy

**Comment by mmjd** [comment]
@joemcelroy is it available in next release?

**Comment by joemcelroy** [comment]
@mmjd take a look at searchkit-universal, thats a working prototype of searchkit working in next.js. The way you integrate it with next.js will improve later on but right now its works today with next.js.

**Comment by ssetem** [comment]
this is ready for testing in v2.3.0-0

example usage can be found here

https://github.com/searchkit/searchkit-examples/tree/master/searchkit-ssr-express-example

thanks all!

**Comment by TheDolo** [comment]
![image](https://user-images.githubusercontent.com/26640355/31570981-a9eb3d5e-b026-11e7-89b5-261b63f285f2.png)

Using older and 2.3.0, passing custom components seems broken.  All above have been passed custom components, yet only one is using it? Only happens when I webpack production build with SSR (https://github.com/FormidableLabs/rapscallion).

**Comment by ssetem** [comment]
we have tested with vanilla express ssr + next.js and seems to work ok.

I see no reason why custom components shouldn't work but if you give us a public repo which reproduces the issue I can take a look

Thanks!

**Comment by Jaikant** [comment]
Works like a charm out of the box 💯 
Thanks for the lovely work!

**Comment by Jaikant** [comment]
I found a problem, I think. If I go to my search link from my home page, it works fine. But if access the search link directly then it gives the below error:

Invariant Violation: Browser history needs a DOM
    at invariant (/Users/jai/work/guides/landing/sf/node_modules/invariant/invariant.js:42:15)
    at Object.createBrowserHistory (/Users/jai/work/guides/landing/sf/node_modules/searchkit/node_modules/history/createBrowserHistory.js:49:27)
    at Object.exports.createHistoryInstance [as createHistory] (/Users/jai/work/guides/landing/sf/node_modules/searchkit/src/core/history.ts:13:10)
    at SearchkitManager.setupListeners (/Users/jai/work/guides/landing/sf/node_modules/searchkit/src/core/SearchkitManager.ts:109:35)
    at SearchkitProvider.componentWillMount (/Users/jai/work/guides/landing/sf/node_modules/searchkit/src/core/react/SearchkitProvider.tsx:22:24)
    at /Users/jai/work/guides/landing/sf/node_modules/react-dom/lib/ReactCompositeComponent.js:345:23
    at measureLifeCyclePerf (/Users/jai/work/guides/landing/sf/node_modules/react-dom/lib/ReactCompositeComponent.js:73:12)
    at ReactCompositeComponentWrapper.performInitialMount (/Users/jai/work/guides/landing/sf/node_modules/react-dom/lib/ReactCompositeComponent.js:344:9)
    at ReactCompositeComponentWrapper.mountComponent (/Users/jai/work/guides/landing/sf/node_modules/react-dom/lib/ReactCompositeComponent.js:255:21)
    at Object.mountComponent (/Users/jai/work/guides/landing/sf/node_modules/react-dom/lib/ReactReconciler.js:43:35)
    at ReactCompositeComponentWrapper.performInitialMount (/Users/jai/work/guides/landing/sf/node_modules/react-dom/lib/ReactCompositeComponent.js:368:34)
    at ReactCompositeComponentWrapper.mountComponent (/Users/jai/work/guides/landing/sf/node_modules/react-dom/lib/ReactCompositeComponent.js:255:21)
    at Object.mountComponent (/Users/jai/work/guides/landing/sf/node_modules/react-dom/lib/ReactReconciler.js:43:35)
    at ReactCompositeComponentWrapper.performInitialMount (/Users/jai/work/guides/landing/sf/node_modules/react-dom/lib/ReactCompositeComponent.js:368:34)
    at ReactCompositeComponentWrapper.mountComponent (/Users/jai/work/guides/landing/sf/node_modules/react-dom/lib/ReactCompositeComponent.js:255:21)
    at Object.mountComponent (/Users/jai/work/guides/landing/sf/node_modules/react-dom/lib/ReactReconciler.js:43:35)
    at ReactDOMComponent.mountChildren (/Users/jai/work/guides/landing/sf/node_modules/react-dom/lib/ReactMultiChild.js:234:44)
    at ReactDOMComponent._createContentMarkup (/Users/jai/work/guides/landing/sf/node_modules/react-dom/lib/ReactDOMComponent.js:657:32)
    at ReactDOMComponent.mountComponent (/Users/jai/work/guides/landing/sf/node_modules/react-dom/lib/ReactDOMComponent.js:524:29)
    at Object.mountComponent (/Users/jai/work/guides/landing/sf/node_modules/react-dom/lib/ReactReconciler.js:43:35)
    at ReactCompositeComponentWrapper.performInitialMount (/Users/jai/work/guides/landing/sf/node_modules/react-dom/lib/ReactCompositeComponent.js:368:34)
    at ReactCompositeComponentWrapper.mountComponent (/Users/jai/work/guides/landing/sf/node_modules/react-dom/lib/ReactCompositeComponent.js:255:21)
    at Object.mountComponent (/Users/jai/work/guides/landing/sf/node_modules/react-dom/lib/ReactReconciler.js:43:35)
    at ReactDOMComponent.mountChildren (/Users/jai/work/guides/landing/sf/node_modules/react-dom/lib/ReactMultiChild.js:234:44)
    at ReactDOMComponent._createContentMarkup (/Users/jai/work/guides/landing/sf/node_modules/react-dom/lib/ReactDOMComponent.js:657:32)
    at ReactDOMComponent.mountComponent (/Users/jai/work/guides/landing/sf/node_modules/react-dom/lib/ReactDOMComponent.js:524:29)
    at Object.mountComponent (/Users/jai/work/guides/landing/sf/node_modules/react-dom/lib/ReactReconciler.js:43:35)
    at ReactDOMComponent.mountChildren (/Users/jai/work/guides/landing/sf/node_modules/react-dom/lib/ReactMultiChild.js:234:44)
    at ReactDOMComponent._createContentMarkup (/Users/jai/work/guides/landing/sf/node_modules/react-dom/lib/ReactDOMComponent.js:657:32)
    at ReactDOMComponent.mountComponent (/Users/jai/work/guides/landing/sf/node_modules/react-dom/lib/ReactDOMComponent.js:524:29)
    at Object.mountComponent (/Users/jai/work/guides/landing/sf/node_modules/react-dom/lib/ReactReconciler.js:43:35)
    at ReactDOMComponent.mountChildren (/Users/jai/work/guides/landing/sf/node_modules/react-dom/lib/ReactMultiChild.js:234:44)
    at ReactDOMComponent._createContentMarkup (/Users/jai/work/guides/landing/sf/node_modules/react-dom/lib/ReactDOMComponent.js:657:32)
    at ReactDOMComponent.mountComponent (/Users/jai/work/guides/landing/sf/node_modules/react-dom/lib/ReactDOMComponent.js:524:29)

You can take a look at it here:  [https://sherpafeet.com](https://sherpafeet.com) if we click the "search guides" it works allright. But if we directly go to [https://sherpafeet.com/guides](https://sherpafeet.com/guides) we get the above error.

**Comment by ssetem** [comment]
If you are using react router, need to use StaticRouter on server, BrowserRouter on client

**Comment by Jaikant** [comment]
I am using RSK which uses the universal router.  [https://github.com/kriasoft/universal-router](https://github.com/kriasoft/universal-router)

**Comment by ssetem** [comment]
I see, you might need to override createHistory option when constructing searchkit

```js
let searchkit = new SearchkitManager(host, {
  createHistory:()=> //returns memory history on server
})
```

we can look to detecting the environment, but try this in the meantime

**Comment by ssetem** [comment]
Also @Jaikant you probably can switch history off on server

```js
let searchkit = new SearchkitManager(host, {useHistory:false})
```

it should be like that in our example code

**Comment by Jaikant** [comment]
@ssetem thanks I set the userHistory: false on the server.
