### ISSUE TITLE
Examples page is not working

### ISSUE THREAD

**Issue by Somebi** [searchkit/searchkit#652]
http://docs.searchkit.co/stable/examples/

Some errors in console:
```
docs.searchkit.co/:20 GET http://docs.searchkit.co/stable/gitbook/gitbook-plugin-mermaid-2/bower_components/mermaid/dist/mermaid.css 404 (Not Found)
gitbook.js:4 page has changed {page: {…}, config: {…}, file: {…}, gitbook: {…}, basePath: "..", …}
gitbook.js:2 jQuery.Deferred exception: Cannot read property 'getEngine' of undefined TypeError: Cannot read property 'getEngine' of undefined
    at Object.<anonymous> (http://docs.searchkit.co/stable/gitbook/gitbook-plugin-lunr/search-lunr.js:54:37)
    at Object.dispatch (http://docs.searchkit.co/stable/gitbook/gitbook.js:2:19320)
    at Object.m.handle (http://docs.searchkit.co/stable/gitbook/gitbook.js:2:17339)
    at Object.trigger (http://docs.searchkit.co/stable/gitbook/gitbook.js:3:8538)
    at Object.<anonymous> (http://docs.searchkit.co/stable/gitbook/gitbook.js:3:9059)
    at Function.each (http://docs.searchkit.co/stable/gitbook/gitbook.js:1:15309)
    at de.fn.init.each (http://docs.searchkit.co/stable/gitbook/gitbook.js:1:13477)
    at de.fn.init.trigger (http://docs.searchkit.co/stable/gitbook/gitbook.js:3:9034)
    at Object.r [as hasChanged] (http://docs.searchkit.co/stable/gitbook/gitbook.js:4:8170)
    at http://docs.searchkit.co/stable/examples/:1111:26 undefined
de.Deferred.exceptionHook @ gitbook.js:2
p @ gitbook.js:2
setTimeout (async)
(anonymous) @ gitbook.js:2
c @ gitbook.js:2
fireWith @ gitbook.js:2
fire @ gitbook.js:2
c @ gitbook.js:2
fireWith @ gitbook.js:2
ready @ gitbook.js:2
l @ gitbook.js:1
gitbook.js:2 Uncaught TypeError: Cannot read property 'getEngine' of undefined
    at Object.<anonymous> (search-lunr.js:54)
    at Object.dispatch (gitbook.js:2)
    at Object.m.handle (gitbook.js:2)
    at Object.trigger (gitbook.js:3)
    at Object.<anonymous> (gitbook.js:3)
    at Function.each (gitbook.js:1)
    at de.fn.init.each (gitbook.js:1)
    at de.fn.init.trigger (gitbook.js:3)
    at Object.r [as hasChanged] (gitbook.js:4)
    at (index):1111
```

**Comment by shawnco** [comment]
I can second this. In fact it looks like anything embedded from Codepen is failing to show up as well.

**Comment by kud** [comment]
That's normal. It's because codepen is in https and the ajax requests from searchkit are done on another domain in http, so CORS troubles.
