### ISSUE TITLE
Issues in examples/next

### ISSUE THREAD

**Issue by mausch** [searchkit/searchkit#852]
Hi and thanks for all your work on this project!

When I run `npm run start` in https://github.com/searchkit/searchkit/tree/next/examples/next I'm getting:

```
TypeError: _searchkit_schema__WEBPACK_IMPORTED_MODULE_2__.GeoBoundingBoxFilter is not a constructor
    at eval (webpack-internal:///./pages/api/graphql.js:107:13)
    at Module../pages/api/graphql.js (/home/mauricio/prg/searchkit/examples/next/.next/server/pages/api/graphql.js:104:1)
    at __webpack_require__ (/home/mauricio/prg/searchkit/examples/next/.next/server/pages/api/graphql.js:23:31)
    at /home/mauricio/prg/searchkit/examples/next/.next/server/pages/api/graphql.js:91:18
    at Object.<anonymous> (/home/mauricio/prg/searchkit/examples/next/.next/server/pages/api/graphql.js:94:10)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at DevServer.handleApiRequest (/home/mauricio/prg/searchkit/examples/next/node_modules/next/dist/next-server/server/next-server.js:64:181)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async Object.fn (/home/mauricio/prg/searchkit/examples/next/node_modules/next/dist/next-server/server/next-server.js:56:492)
    at async Router.execute (/home/mauricio/prg/searchkit/examples/next/node_modules/next/dist/next-server/server/router.js:23:67)
```

When I run `npm run build`:

`ModuleNotFoundError: Module not found: Error: Can't resolve './PlacesSearchInput' in '/home/mauricio/prg/searchkit/examples/next/components/geosearch-examples'
`

I had to remove that PlacesSearchInput component to get it to build.

**Comment by joemcelroy** [comment]
hey @mausch Yes - this is because next branch right now is a little WIP on a geosearch example api im building and relies on an unreleased version of @searchkit/schema. 

To fix, i would update the graphql/api file with the previous commit, that should work https://github.com/searchkit/searchkit/blob/7d525eee46bb5cb63224376aff529abf7ff62be5/examples/next/pages/api/graphql.js

Next is getting a bit complicated as starting to drive many examples so i do plan to have another next example which is much more simplified.
