### ISSUE TITLE
How to do search in string array?

### ISSUE THREAD

**Issue by lutaev** [searchkit/searchkit#941]
Hi everyone.

Thanks for your project, it is really usefull. I'm not very strong in elasticsearch, so I please about help. I use the Searchkit in my NextJS app and I have some items in ES index looks like this:
```
{
  "id" : "g6a7s6d76asd",
  "text" : "Test",
  "tags" : ['tag_1',  'tag_2' ],
}
```
So, I want to get `tag_1` and `tag_2` as a facet results. My searchkit config is:
```
const fields = ['id', 'text', 'tags'];
const index = process.env.NEXT_PUBLIC_ES_INDEX;

const searchkitConfig = createSearchkitConfig(index, fields, [{
  field: 'tags',
  identifier: 'tags',
  label: 'Tags'
}]);
```
and my type defs are:
```
typeDefs: [
  gql`
    type Query {
      root: String
    }

    type HitFields {
      id: String
      text: String
      tags: [String]
    }

    type ResultHit implements SKHit {
      id: ID!
      fields: HitFields
    }
  `, ...typeDefs
]
```
then if I do request:
```
{
  results {
    hits {
      items {
        ... on ResultHit {
          id
          fields {
            id
            text
            tags
          }
        }
      }
    } 
  }
}
```
I get correct results. 
But if I add facets:
```
{
  results {
    hits {
      items {
        ... on ResultHit {
          id
          fields {
            id
            text
            tags
          }
        }
      }
    } 
    facets {
      identifier
      label
    }
  }
}
```
I get null result and an error in my nextJS console:
```
ResponseError: search_phase_execution_exception
    at onBody (/Users/imac/WebstormProjects/insightflow-app/node_modules/@elastic/elasticsearch/lib/Transport.js:337:23)
    at IncomingMessage.onEnd (/Users/imac/WebstormProjects/insightflow-app/node_modules/@elastic/elasticsearch/lib/Transport.js:264:11)
    at IncomingMessage.emit (events.js:322:22)
    at endReadableNT (_stream_readable.js:1187:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:21) {
  meta: {
    body: { error: [Object], status: 400 },
    statusCode: 400,
    headers: {
      date: 'Mon, 05 Jul 2021 16:28:50 GMT',
      'content-type': 'application/json; charset=UTF-8',
      'content-length': '1439',
      connection: 'keep-alive',
      'access-control-allow-origin': '*'
    },
    meta: {
      context: null,
      request: [Object],
      name: 'elasticsearch-js',
      connection: [Object],
      attempts: 0,
      aborted: false
    }
  }
}
TypeError: Cannot destructure property 'hits' of '(intermediate value)' as it is undefined.
    at /Users/imac/WebstormProjects/insightflow-app/node_modules/@searchkit/schema/lib/resolvers/HitsResolver.js:31:17
    at Generator.next (<anonymous>)
    at fulfilled (/Users/imac/WebstormProjects/insightflow-app/node_modules/@searchkit/schema/lib/resolvers/HitsResolver.js:5:58)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
TypeError: Cannot read property 'aggregations' of undefined
    at Object.getFacetsFromResponse (/Users/imac/WebstormProjects/insightflow-app/node_modules/@searchkit/schema/lib/core/FacetsFns.js:39:50)
    at /Users/imac/WebstormProjects/insightflow-app/node_modules/@searchkit/schema/lib/resolvers/FacetsResolver.js:22:36
    at Generator.next (<anonymous>)
    at fulfilled (/Users/imac/WebstormProjects/insightflow-app/node_modules/@searchkit/schema/lib/resolvers/FacetsResolver.js:5:58)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
```

Thanks

**Comment by joemcelroy** [comment]
hey @lutaev, great to hear!

Could you tell me what `createSearchkitConfig` function does? Looking at the stack trace, its complaining about the setup of the facets. Facets example configuration are shown here https://github.com/searchkit/searchkit/blob/next/examples/next-demo/pages/api/graphql.js#L26

Also you can jump on discord to ask https://discord.gg/CRuWmSQZQx

**Comment by lutaev** [comment]
hey @joemcelroy, thanks for quick answer.

I found the reason, I was trying to find by field indexed not correctly. My bad, so, it can be closed.

**Comment by joemcelroy** [comment]
great to hear @lutaev . Also theres some more information on how to index here too https://dev.to/joemcelroy/search-ui-graphql-api-with-elasticsearch-searchkit-4jp7
