### ISSUE TITLE
Problem implementating CustomFilter

### ISSUE THREAD

**Issue by devolt5** [searchkit/searchkit#971]
In order to create a "**detailed view**" I wanted to create a query, which filters the resultSet by the id (here. "docid") of the item.

I tried to create a new query with a restriction to the "docid"-field - with no success.
Then I read about custom filters (https://searchkit.co/docs/customisations/customisations-filters)

This is nearly copy+paste from the documentation:

```js
class CustomFilter {
  excludeOwnFilters = false

  constructor() {}

  getIdentifier() {
    return "CustomFilter"
  }

  // returns the ES query 
  getFilters(filters) {
    return {
      "should" : filters.map((filter) => {
        return { "term" : {"docid": filter.value }}
      })
    }
  }

  // powers the appliedFilters type for all filters added 
  getSelectedFilter(filterSet) {
    return {
      type: 'ValueSelectedFilter',
      id: `${this.getIdentifier()}_${filterSet.value}`,
      identifier: this.getIdentifier(),
      label: "CustomFilter",
      value: filterSet.value,
      display: "Custom"
    }
  }
}
```
This is my searchkitConfig:

```js
const searchkitConfig = {
  host: process.env.ES_HOST || 'http://localhost:9200',
  index: 'my_index',
  hits: {
    fields: ['author','date_begin','title','docid']
  },
  sortOptions: [
    { id: 'relevance', label: "Relevance", field: [{"_score": "desc"}], defaultOption: true},
    { id: 'date', label: "Date", field: [{"date_begin": "desc"}]},
  ],
  query: new TruncatedQuery({ fields: ['author','title'] }),
  filters: [
    new CustomFilter()
  ],
  facets: [
  ]
}
```

I then tried to query with this new filter, as shown in the documentation:

```gql
{
    results(filters: [{ identifier: "CustomFilter", value: "1" }]) {
        summary {
            appliedFilters {
                id
                identifier
                label
                display
                ... on ValueSelectedFilter {
                    value
                }
            }
        }
        hits {
            items {
                ... on ResultHit {
                    id
                    fields {
                        docid
                        title
                        author
                        date_begin
                    }
                }
            }
        }
    }
}


```
Compilation showed no problems, but when I execute this query in /api/graphql I get this runtime error:

```shell
ResponseError: x_content_parse_exception
    at onBody (prj/node_modules/@elastic/elasticsearch/lib/Transport.js:337:23)
    at IncomingMessage.onEnd (prj/node_modules/@elastic/elasticsearch/lib/Transport.js:264:11)
    at IncomingMessage.emit (events.js:412:35)
    at endReadableNT (internal/streams/readable.js:1317:12)
    at processTicksAndRejections (internal/process/task_queues.js:82:21) {
  meta: {
    body: { error: [Object], status: 400 },
    statusCode: 400,
    headers: {
      'x-elastic-product': 'Elasticsearch',
      'content-type': 'application/json; charset=UTF-8',
      'content-length': '374'
    },
    meta: {
      context: null,
      request: [Object],
      name: 'elasticsearch-js',
      connection: [Object],
      attempts: 0,
      aborted: false
    }
  }
}
TypeError: Cannot read property 'hits' of undefined
    at prj/node_modules/@searchkit/schema/lib/resolvers/SummaryResolver.js:20:35
    at Generator.next (<anonymous>)
    at fulfilled (prj/node_modules/@searchkit/schema/lib/resolvers/SummaryResolver.js:5:58)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
TypeError: Cannot destructure property 'hits' of '(intermediate value)' as it is undefined.
    at prj/node_modules/@searchkit/schema/lib/resolvers/HitsResolver.js:31:17
    at Generator.next (<anonymous>)
    at fulfilled (prj/node_modules/@searchkit/schema/lib/resolvers/HitsResolver.js:5:58)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
```

To doublecheck with the elasticsearch API, I tried this request:

```json
{
  "query": {
    "bool": {
      "should" : [
        { "term" : { "docid" : "1" } }
      ]
    }
  }
}
```

... which was successful:

```json
{
    "took": 0,
    "timed_out": false,
    "_shards": {
        "total": 1,
        "successful": 1,
        "skipped": 0,
        "failed": 0
    },
    "hits": {
        "total": {
            "value": 1,
            "relation": "eq"
        },
        "max_score": 3.9639826,
        "hits": [
            {
                "_index": "my_index",
                "_type": "_doc",
                "_id": "G54geHsBSnBCJ9jo4HMb",
                "_score": 3.9639826,
                "_source": {
                    "docid": 1,
                    "author": "Petrus Abaelardus",
                    "title": "Epistola",
                    "date_begin": 1130,
                }
            }
        ]
    }
}
```
I'm neither a master with graphQL nor searchkit, so I appreciate any ideas or suggestions.
Am I missing something in the query? Or in the implementation?

Thanks!

**Comment by joemcelroy** [comment]
hey @devolt5 😬  might be documentation is incorrect for the `getFilters` method. The best thing now is to get the ES query that searchkit is making (easiest way is to implement postProcessRequest method in searchkitConfig - example here https://searchkit.co/docs/reference/schema#postprocessrequest) 

```
  postProcessRequest: (body) => {
    console.log(body)
    return body
  } 
```
and perform the query to ES to see the full error. I will also make a PR to be able to toggle query error visibility to the user. 

Also you can reach me on discord (https://discord.gg/CRuWmSQZQx) if you have further questions :)

**Comment by devolt5** [comment]
Thanks for the answer!

I solved the issue, but I have a follow-up question. First, my code:

```js
class CustomFilter {
  excludeOwnFilters = false

  constructor(fieldname) {
    this.fieldname = fieldname;
  }

  getIdentifier() {
    return "CustomFilter"
  }

  // returns the ES query 
  getFilters(filters) {
    return { "term" : { [this.fieldname]: filters[0].value }}
  }

  // powers the appliedFilters type for all filters added 
  getSelectedFilter(filterSet) {
    console.log(filterSet);
    return {
      type: 'ValueSelectedFilter',
      id: `${this.getIdentifier()}_${filterSet.value}`,
      identifier: this.getIdentifier(),
      label: "CustomFilter",
      value: filterSet.value,
      display: "Custom"
    }
  }
}
```

I noticed via `postProcessRequest` debugging that there are already some "ES-verbs" defined.
So, it was not possible to use `should`, because `bool` and `must` are already set.

```js
post_filter: { bool: { must: [Array] } },
```
I don't know where `post_filter` is coming into play. But as you see above, I only return the object which gets into the Array.
`{ "term" : { [this.fieldname]: filters[0].value }}`

But here's my follow-up **question**:

As seen in `QueryManager.js`, `getFilters()` returns an Array.
But when I use this code, it does not work:

```js
  getFilters(filters) {
     return filters.map((filter) => {
        return { "term" : {[this.fieldname]: filter.value }}
      })
  }
```
I have to return an object... 
🤔
